<?php

namespace Snijenhuis\Modules\Auth\Providers;

use App;
use Lang;
use View;
use Caffeinated\Modules\Support\ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
	/**
	 * Register the Auth module service provider.
	 *
	 * This service provider is a convenient place to register your modules
	 * services in the IoC container. If you wish, you may make additional
	 * methods or service providers to keep the code more focused and granular.
	 *
	 * @return void
	 */
	public function register()
	{

		$this->mergeConfigFrom(
			__DIR__.'/../Config/auth.php', 'snijenhuis.auth'
		);

		App::register('Snijenhuis\Modules\Auth\Providers\RouteServiceProvider');
		App::register('Snijenhuis\Modules\Auth\Providers\EventServiceProvider');
		App::register('Snijenhuis\Modules\Auth\Providers\ViewComposerServiceProvider');

		/*
		 * Third party modules
		 */
		App::register('Cartalyst\Sentinel\Laravel\SentinelServiceProvider');
		App::register('Laravel\Socialite\SocialiteServiceProvider');
		App::register('Creativeorange\Gravatar\GravatarServiceProvider');

		Lang::addNamespace('auth', realpath(__DIR__.'/../Resources/Lang'));
		View::addNamespace('auth', base_path('resources/views/vendor/auth'));
		View::addNamespace('auth', realpath(__DIR__.'/../Resources/Views'));




	}

	/**
	 * Bootstrap the application events.
	 *
	 * Here you may register any additional middleware provided with your
	 * module with the following addMiddleware() method. You may pass in
	 * either an array or a string.
	 *
	 * @return void
	 */
	public function boot()
	{
		$this->publishes([
			__DIR__.'/../Config/auth.php' => config_path('snijenhuis.auth.php'),
		], 'config');
	}

	/**
	 * Additional Compiled Module Classes
	 *
	 * Here you may specify additional classes to include in the compiled file
	 * generated by the `artisan optimize` command. These should be classes
	 * that are included on basically every request into the application.
	 *
	 * @return array
	 */
	public static function compiles()
	{
		$basePath = realpath(__DIR__.'/../');

		return [
			// $basePath.'/example.php',
		];
	}
}
